"""
Report Generator
Generates professional HTML and JSON audit reports.
"""

from __future__ import annotations
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional
from ..utils.logger import get_logger

logger = get_logger(__name__)


# Severity color mapping for HTML output
SEVERITY_COLORS = {
    "CRITICAL": "#dc2626",
    "HIGH": "#ea580c",
    "MEDIUM": "#ca8a04",
    "LOW": "#2563eb",
    "INFO": "#6b7280",
}

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MiMo Sentinel Audit Report</title>
<style>
body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }}
.container {{ max-width: 900px; margin: 0 auto; }}
h1 {{ color: #38bdf8; border-bottom: 2px solid #1e3a5f; padding-bottom: 1rem; }}
h2 {{ color: #7dd3fc; margin-top: 2rem; }}
.badge {{ display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 0.85em; font-weight: bold; color: white; }}
.badge-critical {{ background: {critical_color}; }}
.badge-high {{ background: {high_color}; }}
.badge-medium {{ background: {medium_color}; }}
.badge-low {{ background: {low_color}; }}
.badge-info {{ background: {info_color}; }}
.finding {{ background: #1e293b; border-left: 4px solid; padding: 1rem; margin: 1rem 0; border-radius: 4px; }}
.summary-grid {{ display: grid; grid-template-columns: repeat(5, 1fr); gap: 1rem; margin: 1rem 0; }}
.summary-card {{ background: #1e293b; padding: 1rem; border-radius: 8px; text-align: center; }}
.summary-card .count {{ font-size: 2em; font-weight: bold; }}
table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
th, td {{ padding: 0.75rem; text-align: left; border-bottom: 1px solid #334155; }}
th {{ background: #1e293b; color: #94a3b8; }}
.footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #334155; color: #64748b; font-size: 0.9em; }}
</style>
</head>
<body>
<div class="container">
<h1>🛡️ MiMo Sentinel Audit Report</h1>
<p><strong>Contract:</strong> {contract_name} | <strong>Date:</strong> {date} | <strong>Score:</strong> {score}/100</p>

<h2>Summary</h2>
<div class="summary-grid">{summary_cards}</div>

<h2>Findings ({total_findings})</h2>
{findings_html}

<h2>Gas Optimization</h2>
{gas_section}

<div class="footer">
<p>Generated by MiMo Sentinel Audit v1.0 | MiMo 100T Token Creator Incentive Program</p>
</div>
</div>
</body>
</html>"""


class ReportGenerator:
    """Generates audit reports in HTML and JSON formats."""

    def __init__(
        self,
        contract_name: str,
        findings: list[dict[str, Any]],
        gas_suggestions: Optional[list[dict[str, Any]]] = None,
        ai_analysis: Optional[str] = None,
    ) -> None:
        self.contract_name = contract_name
        self.findings = findings
        self.gas_suggestions = gas_suggestions or []
        self.ai_analysis = ai_analysis
        self.timestamp = datetime.now(timezone.utc).isoformat()

    def generate_html(self, output_path: str) -> str:
        """Generate an HTML audit report."""
        logger.info(f"Generating HTML report: {output_path}")
        summary = self._get_summary()
        summary_cards = self._render_summary_cards(summary)
        findings_html = self._render_findings()
        gas_section = self._render_gas_section()
        score = self._calculate_score()

        html = HTML_TEMPLATE.format(
            contract_name=self.contract_name,
            date=self.timestamp[:10],
            score=score,
            total_findings=len(self.findings),
            summary_cards=summary_cards,
            findings_html=findings_html,
            gas_section=gas_section,
            critical_color=SEVERITY_COLORS["CRITICAL"],
            high_color=SEVERITY_COLORS["HIGH"],
            medium_color=SEVERITY_COLORS["MEDIUM"],
            low_color=SEVERITY_COLORS["LOW"],
            info_color=SEVERITY_COLORS["INFO"],
        )
        Path(output_path).write_text(html)
        logger.info(f"Report saved: {output_path}")
        return output_path

    def generate_json(self, output_path: str) -> str:
        """Generate a JSON audit report."""
        report = {
            "contract": self.contract_name,
            "timestamp": self.timestamp,
            "score": self._calculate_score(),
            "summary": self._get_summary(),
            "findings": self.findings,
            "gas_suggestions": self.gas_suggestions,
            "ai_analysis": self.ai_analysis,
        }
        Path(output_path).write_text(json.dumps(report, indent=2))
        logger.info(f"JSON report saved: {output_path}")
        return output_path

    def _get_summary(self) -> dict[str, int]:
        """Count findings by severity."""
        summary = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
        for f in self.findings:
            sev = f.get("severity", "INFO")
            summary[sev] = summary.get(sev, 0) + 1
        return summary

    def _calculate_score(self) -> int:
        """Calculate overall security score (100 = perfect)."""
        deductions = {"CRITICAL": 20, "HIGH": 12, "MEDIUM": 5, "LOW": 2, "INFO": 0}
        total_deduction = sum(
            deductions.get(f.get("severity", "INFO"), 0) for f in self.findings
        )
        return max(0, 100 - total_deduction)

    def _render_summary_cards(self, summary: dict[str, int]) -> str:
        """Render HTML summary cards."""
        cards = ""
        for sev, count in summary.items():
            color = SEVERITY_COLORS.get(sev, "#6b7280")
            cards += (
                f'<div class="summary-card">'
                f'<div class="count" style="color:{color}">{count}</div>'
                f'<div>{sev}</div></div>'
            )
        return cards

    def _render_findings(self) -> str:
        """Render findings as HTML."""
        html = ""
        for f in self.findings:
            sev = f.get("severity", "INFO")
            color = SEVERITY_COLORS.get(sev, "#6b7280")
            badge_class = sev.lower()
            html += (
                f'<div class="finding" style="border-color:{color}">'
                f'<span class="badge badge-{badge_class}">{sev}</span> '
                f'<strong>{f.get("vuln_type", "Unknown")}</strong> — '
                f'Line {f.get("line", "?")}<br>'
                f'<p>{f.get("message", "")}</p>'
            )
            if f.get("recommendation"):
                html += f'<p><em>💡 {f["recommendation"]}</em></p>'
            html += "</div>"
        return html or "<p>No findings — contract looks clean!</p>"

    def _render_gas_section(self) -> str:
        """Render gas optimization suggestions."""
        if not self.gas_suggestions:
            return "<p>No gas optimization opportunities found.</p>"
        html = "<table><tr><th>Pattern</th><th>Line</th><th>Suggestion</th><th>Savings</th></tr>"
        for g in self.gas_suggestions[:10]:
            savings = g.get("savings_percent", 0)
            html += (
                f'<tr><td>{g.get("pattern", "")}</td>'
                f'<td>{g.get("line", "")}</td>'
                f'<td>{g.get("suggestion", "")}</td>'
                f'<td>{savings:.0f}%</td></tr>'
            )
        html += "</table>"
        return html

    def get_summary_text(self) -> str:
        """Generate a plain text summary."""
        summary = self._get_summary()
        score = self._calculate_score()
        lines = [
            f"MiMo Sentinel Audit Report — {self.contract_name}",
            f"{'='*50}",
            f"Date: {self.timestamp[:10]} | Score: {score}/100",
            f"CRITICAL: {summary['CRITICAL']} | HIGH: {summary['HIGH']} | "
            f"MEDIUM: {summary['MEDIUM']} | LOW: {summary['LOW']}",
        ]
        return "\n".join(lines)
